### ISSUE TITLE
Incorrect value for memory limit in unstable-pod.yaml

### ISSUE THREAD

**Issue by gmwubs** [elle-la/ckad_4#5]
In the pod definition: 
```
    resources:
      requests:
        cpu: "100m"
        memory: "50Mi"
      limits:
        cpu: "200m"
        memory: "100Gi"
```
So it is no surprise one will not see the pod run into any issue. At least: as long as one of the cluster nodes has at least 100Gi available and the pod will start using it. I think 100Gi should have been 100Mi .

**Comment by gmwubs** [comment]
Perhaps it should even be 100Ki, since the pod doesn't appear to be unstable at all.

**Comment by gmwubs** [comment]
After some tinkering, I managed to get the pod status becoming ChrashLoopBackOff with the following limits: 
```
    resources:
      requests:
        cpu: "100m"
        memory: "500Ki"
      limits:
        cpu: "200m"
        memory: "1Mi"
```
